[processor.make]
exclude_files = ["Makefile"]

[processor.yamllint]
enabled = false

[processor.mdl]
enabled = false

[processor.pyrefly]
enabled = false

[processor.markdownlint]
enabled = false

[processor.ascii_check]
enabled = false

[processor.a2x]
enabled = false

[processor.marp]
enabled = false

[processor.rumdl]
enabled = false

[processor.slidev]
enabled = false

[processor.tidy]
enabled = false

[processor.htmlhint]
enabled = false

[processor.htmllint]
enabled = false
